// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protofiles/serverConnectionService.proto

package serverConnection

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CHANGE_TYPE int32

const (
	CHANGE_TYPE_New    CHANGE_TYPE = 0
	CHANGE_TYPE_Change CHANGE_TYPE = 1
	CHANGE_TYPE_Remove CHANGE_TYPE = 2
)

// Enum value maps for CHANGE_TYPE.
var (
	CHANGE_TYPE_name = map[int32]string{
		0: "New",
		1: "Change",
		2: "Remove",
	}
	CHANGE_TYPE_value = map[string]int32{
		"New":    0,
		"Change": 1,
		"Remove": 2,
	}
)

func (x CHANGE_TYPE) Enum() *CHANGE_TYPE {
	p := new(CHANGE_TYPE)
	*p = x
	return p
}

func (x CHANGE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CHANGE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_serverConnectionService_proto_enumTypes[0].Descriptor()
}

func (CHANGE_TYPE) Type() protoreflect.EnumType {
	return &file_protofiles_serverConnectionService_proto_enumTypes[0]
}

func (x CHANGE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CHANGE_TYPE.Descriptor instead.
func (CHANGE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{0}
}

type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=Ping,proto3" json:"Ping,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{0}
}

func (x *CheckReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge string `protobuf:"bytes,1,opt,name=Challenge,proto3" json:"Challenge,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{1}
}

func (x *AuthReq) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

type CheckRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=Pong,proto3" json:"Pong,omitempty"`
}

func (x *CheckRes) Reset() {
	*x = CheckRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRes) ProtoMessage() {}

func (x *CheckRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRes.ProtoReflect.Descriptor instead.
func (*CheckRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRes) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type AuthRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *AuthRes) Reset() {
	*x = AuthRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRes) ProtoMessage() {}

func (x *AuthRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRes.ProtoReflect.Descriptor instead.
func (*AuthRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{3}
}

func (x *AuthRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ServerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalID int32  `protobuf:"varint,1,opt,name=InternalID,proto3" json:"InternalID,omitempty"`
	Public_IP  string `protobuf:"bytes,2,opt,name=Public_IP,json=PublicIP,proto3" json:"Public_IP,omitempty"`
	Private_IP string `protobuf:"bytes,3,opt,name=Private_IP,json=PrivateIP,proto3" json:"Private_IP,omitempty"`
}

func (x *ServerData) Reset() {
	*x = ServerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerData) ProtoMessage() {}

func (x *ServerData) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerData.ProtoReflect.Descriptor instead.
func (*ServerData) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{4}
}

func (x *ServerData) GetInternalID() int32 {
	if x != nil {
		return x.InternalID
	}
	return 0
}

func (x *ServerData) GetPublic_IP() string {
	if x != nil {
		return x.Public_IP
	}
	return ""
}

func (x *ServerData) GetPrivate_IP() string {
	if x != nil {
		return x.Private_IP
	}
	return ""
}

type ServerInfoUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            CHANGE_TYPE `protobuf:"varint,1,opt,name=Type,proto3,enum=halalwedd_managing_server.CHANGE_TYPE" json:"Type,omitempty"`
	ChangedServerID int32       `protobuf:"varint,2,opt,name=ChangedServerID,proto3" json:"ChangedServerID,omitempty"`
	ServerData      *ServerData `protobuf:"bytes,3,opt,name=ServerData,proto3" json:"ServerData,omitempty"`
}

func (x *ServerInfoUpdate) Reset() {
	*x = ServerInfoUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoUpdate) ProtoMessage() {}

func (x *ServerInfoUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoUpdate.ProtoReflect.Descriptor instead.
func (*ServerInfoUpdate) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfoUpdate) GetType() CHANGE_TYPE {
	if x != nil {
		return x.Type
	}
	return CHANGE_TYPE_New
}

func (x *ServerInfoUpdate) GetChangedServerID() int32 {
	if x != nil {
		return x.ChangedServerID
	}
	return 0
}

func (x *ServerInfoUpdate) GetServerData() *ServerData {
	if x != nil {
		return x.ServerData
	}
	return nil
}

type DataUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DataUpdateRes) Reset() {
	*x = DataUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverConnectionService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUpdateRes) ProtoMessage() {}

func (x *DataUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverConnectionService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUpdateRes.ProtoReflect.Descriptor instead.
func (*DataUpdateRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverConnectionService_proto_rawDescGZIP(), []int{6}
}

func (x *DataUpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protofiles_serverConnectionService_proto protoreflect.FileDescriptor

var file_protofiles_serverConnectionService_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x68, 0x61, 0x6c, 0x61,
	0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1e, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x27, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x1e,
	0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x21,
	0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x68, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x12,
	0x1b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x12, 0x1d, 0x0a, 0x0a,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x50, 0x22, 0xbf, 0x01, 0x0a, 0x10,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x3a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26,
	0x2e, 0x68, 0x61, 0x6c, 0x61, 0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x48, 0x41, 0x4e, 0x47,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x45, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x61, 0x6c,
	0x61, 0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a,
	0x0d, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x2e, 0x0a, 0x0b, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x10, 0x02, 0x32, 0xa5, 0x02, 0x0a, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x56, 0x0a, 0x0a, 0x70,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x68, 0x61, 0x6c, 0x61,
	0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x23,
	0x2e, 0x68, 0x61, 0x6c, 0x61, 0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x56, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x68, 0x61, 0x6c, 0x61, 0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x68, 0x61, 0x6c, 0x61, 0x6c, 0x77,
	0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x63, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x2e, 0x68, 0x61, 0x6c, 0x61,
	0x6c, 0x77, 0x65, 0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x28, 0x2e, 0x68, 0x61, 0x6c, 0x61, 0x6c, 0x77, 0x65,
	0x64, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x42, 0x13, 0x5a, 0x11, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_serverConnectionService_proto_rawDescOnce sync.Once
	file_protofiles_serverConnectionService_proto_rawDescData = file_protofiles_serverConnectionService_proto_rawDesc
)

func file_protofiles_serverConnectionService_proto_rawDescGZIP() []byte {
	file_protofiles_serverConnectionService_proto_rawDescOnce.Do(func() {
		file_protofiles_serverConnectionService_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_serverConnectionService_proto_rawDescData)
	})
	return file_protofiles_serverConnectionService_proto_rawDescData
}

var file_protofiles_serverConnectionService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofiles_serverConnectionService_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protofiles_serverConnectionService_proto_goTypes = []interface{}{
	(CHANGE_TYPE)(0),         // 0: halalwedd_managing_server.CHANGE_TYPE
	(*CheckReq)(nil),         // 1: halalwedd_managing_server.CheckReq
	(*AuthReq)(nil),          // 2: halalwedd_managing_server.AuthReq
	(*CheckRes)(nil),         // 3: halalwedd_managing_server.CheckRes
	(*AuthRes)(nil),          // 4: halalwedd_managing_server.AuthRes
	(*ServerData)(nil),       // 5: halalwedd_managing_server.ServerData
	(*ServerInfoUpdate)(nil), // 6: halalwedd_managing_server.ServerInfoUpdate
	(*DataUpdateRes)(nil),    // 7: halalwedd_managing_server.DataUpdateRes
}
var file_protofiles_serverConnectionService_proto_depIdxs = []int32{
	0, // 0: halalwedd_managing_server.ServerInfoUpdate.Type:type_name -> halalwedd_managing_server.CHANGE_TYPE
	5, // 1: halalwedd_managing_server.ServerInfoUpdate.ServerData:type_name -> halalwedd_managing_server.ServerData
	1, // 2: halalwedd_managing_server.serverChecking.pingServer:input_type -> halalwedd_managing_server.CheckReq
	2, // 3: halalwedd_managing_server.serverChecking.verifyServer:input_type -> halalwedd_managing_server.AuthReq
	6, // 4: halalwedd_managing_server.serverChecking.dataUpdate:input_type -> halalwedd_managing_server.ServerInfoUpdate
	3, // 5: halalwedd_managing_server.serverChecking.pingServer:output_type -> halalwedd_managing_server.CheckRes
	4, // 6: halalwedd_managing_server.serverChecking.verifyServer:output_type -> halalwedd_managing_server.AuthRes
	7, // 7: halalwedd_managing_server.serverChecking.dataUpdate:output_type -> halalwedd_managing_server.DataUpdateRes
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protofiles_serverConnectionService_proto_init() }
func file_protofiles_serverConnectionService_proto_init() {
	if File_protofiles_serverConnectionService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_serverConnectionService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverConnectionService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_serverConnectionService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_serverConnectionService_proto_goTypes,
		DependencyIndexes: file_protofiles_serverConnectionService_proto_depIdxs,
		EnumInfos:         file_protofiles_serverConnectionService_proto_enumTypes,
		MessageInfos:      file_protofiles_serverConnectionService_proto_msgTypes,
	}.Build()
	File_protofiles_serverConnectionService_proto = out.File
	file_protofiles_serverConnectionService_proto_rawDesc = nil
	file_protofiles_serverConnectionService_proto_goTypes = nil
	file_protofiles_serverConnectionService_proto_depIdxs = nil
}
