// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protofiles/serverManaging.proto

package serverManagingService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The server-type enum
type SERVER_TYPE int32

const (
	SERVER_TYPE_NOT_PROVIDED SERVER_TYPE = 0
	SERVER_TYPE_REALTIME     SERVER_TYPE = 1
	SERVER_TYPE_INTERACTION  SERVER_TYPE = 2
	SERVER_TYPE_DATA         SERVER_TYPE = 3
)

// Enum value maps for SERVER_TYPE.
var (
	SERVER_TYPE_name = map[int32]string{
		0: "NOT_PROVIDED",
		1: "REALTIME",
		2: "INTERACTION",
		3: "DATA",
	}
	SERVER_TYPE_value = map[string]int32{
		"NOT_PROVIDED": 0,
		"REALTIME":     1,
		"INTERACTION":  2,
		"DATA":         3,
	}
)

func (x SERVER_TYPE) Enum() *SERVER_TYPE {
	p := new(SERVER_TYPE)
	*p = x
	return p
}

func (x SERVER_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SERVER_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_serverManaging_proto_enumTypes[0].Descriptor()
}

func (SERVER_TYPE) Type() protoreflect.EnumType {
	return &file_protofiles_serverManaging_proto_enumTypes[0]
}

func (x SERVER_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SERVER_TYPE.Descriptor instead.
func (SERVER_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{0}
}

// Exit types enum
type EXIT_TYPE int32

const (
	EXIT_TYPE_NORMAL EXIT_TYPE = 0
	EXIT_TYPE_ERROR  EXIT_TYPE = 1
)

// Enum value maps for EXIT_TYPE.
var (
	EXIT_TYPE_name = map[int32]string{
		0: "NORMAL",
		1: "ERROR",
	}
	EXIT_TYPE_value = map[string]int32{
		"NORMAL": 0,
		"ERROR":  1,
	}
)

func (x EXIT_TYPE) Enum() *EXIT_TYPE {
	p := new(EXIT_TYPE)
	*p = x
	return p
}

func (x EXIT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EXIT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_serverManaging_proto_enumTypes[1].Descriptor()
}

func (EXIT_TYPE) Type() protoreflect.EnumType {
	return &file_protofiles_serverManaging_proto_enumTypes[1]
}

func (x EXIT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EXIT_TYPE.Descriptor instead.
func (EXIT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{1}
}

// Update type enum
type UPDATE_TYPE int32

const (
	UPDATE_TYPE_New    UPDATE_TYPE = 0
	UPDATE_TYPE_Change UPDATE_TYPE = 1
	UPDATE_TYPE_Remove UPDATE_TYPE = 2
)

// Enum value maps for UPDATE_TYPE.
var (
	UPDATE_TYPE_name = map[int32]string{
		0: "New",
		1: "Change",
		2: "Remove",
	}
	UPDATE_TYPE_value = map[string]int32{
		"New":    0,
		"Change": 1,
		"Remove": 2,
	}
)

func (x UPDATE_TYPE) Enum() *UPDATE_TYPE {
	p := new(UPDATE_TYPE)
	*p = x
	return p
}

func (x UPDATE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UPDATE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_serverManaging_proto_enumTypes[2].Descriptor()
}

func (UPDATE_TYPE) Type() protoreflect.EnumType {
	return &file_protofiles_serverManaging_proto_enumTypes[2]
}

func (x UPDATE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UPDATE_TYPE.Descriptor instead.
func (UPDATE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{2}
}

// The general proto message for handling server data(to be used in an array while storing/transaction)
type ServerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InternalID int32  `protobuf:"varint,1,opt,name=InternalID,proto3" json:"InternalID,omitempty"`
	Public_IP  string `protobuf:"bytes,2,opt,name=Public_IP,json=PublicIP,proto3" json:"Public_IP,omitempty"`
	Private_IP string `protobuf:"bytes,3,opt,name=Private_IP,json=PrivateIP,proto3" json:"Private_IP,omitempty"`
}

func (x *ServerData) Reset() {
	*x = ServerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerData) ProtoMessage() {}

func (x *ServerData) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerData.ProtoReflect.Descriptor instead.
func (*ServerData) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{0}
}

func (x *ServerData) GetInternalID() int32 {
	if x != nil {
		return x.InternalID
	}
	return 0
}

func (x *ServerData) GetPublic_IP() string {
	if x != nil {
		return x.Public_IP
	}
	return ""
}

func (x *ServerData) GetPrivate_IP() string {
	if x != nil {
		return x.Private_IP
	}
	return ""
}

// The PublishServer RPC's request message
type PublishServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       SERVER_TYPE `protobuf:"varint,1,opt,name=Type,proto3,enum=serverManagingService.SERVER_TYPE" json:"Type,omitempty"`
	Public_IP  string      `protobuf:"bytes,2,opt,name=Public_IP,json=PublicIP,proto3" json:"Public_IP,omitempty"`
	Private_IP string      `protobuf:"bytes,3,opt,name=Private_IP,json=PrivateIP,proto3" json:"Private_IP,omitempty"`
}

func (x *PublishServerReq) Reset() {
	*x = PublishServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishServerReq) ProtoMessage() {}

func (x *PublishServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishServerReq.ProtoReflect.Descriptor instead.
func (*PublishServerReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{1}
}

func (x *PublishServerReq) GetType() SERVER_TYPE {
	if x != nil {
		return x.Type
	}
	return SERVER_TYPE_NOT_PROVIDED
}

func (x *PublishServerReq) GetPublic_IP() string {
	if x != nil {
		return x.Public_IP
	}
	return ""
}

func (x *PublishServerReq) GetPrivate_IP() string {
	if x != nil {
		return x.Private_IP
	}
	return ""
}

// The PublishServer RPC's response message
type PublishServerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string        `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	InternalID int32         `protobuf:"varint,2,opt,name=InternalID,proto3" json:"InternalID,omitempty"`
	ServerData []*ServerData `protobuf:"bytes,3,rep,name=ServerData,proto3" json:"ServerData,omitempty"`
}

func (x *PublishServerRes) Reset() {
	*x = PublishServerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishServerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishServerRes) ProtoMessage() {}

func (x *PublishServerRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishServerRes.ProtoReflect.Descriptor instead.
func (*PublishServerRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{2}
}

func (x *PublishServerRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PublishServerRes) GetInternalID() int32 {
	if x != nil {
		return x.InternalID
	}
	return 0
}

func (x *PublishServerRes) GetServerData() []*ServerData {
	if x != nil {
		return x.ServerData
	}
	return nil
}

// The NotifyExit RPC's request message
type NotifyExitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       EXIT_TYPE   `protobuf:"varint,1,opt,name=Type,proto3,enum=serverManagingService.EXIT_TYPE" json:"Type,omitempty"`
	SType      SERVER_TYPE `protobuf:"varint,2,opt,name=SType,proto3,enum=serverManagingService.SERVER_TYPE" json:"SType,omitempty"`
	InternalID int32       `protobuf:"varint,3,opt,name=InternalID,proto3" json:"InternalID,omitempty"`
	PublicIP   string      `protobuf:"bytes,4,opt,name=PublicIP,proto3" json:"PublicIP,omitempty"`
}

func (x *NotifyExitReq) Reset() {
	*x = NotifyExitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyExitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyExitReq) ProtoMessage() {}

func (x *NotifyExitReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyExitReq.ProtoReflect.Descriptor instead.
func (*NotifyExitReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyExitReq) GetType() EXIT_TYPE {
	if x != nil {
		return x.Type
	}
	return EXIT_TYPE_NORMAL
}

func (x *NotifyExitReq) GetSType() SERVER_TYPE {
	if x != nil {
		return x.SType
	}
	return SERVER_TYPE_NOT_PROVIDED
}

func (x *NotifyExitReq) GetInternalID() int32 {
	if x != nil {
		return x.InternalID
	}
	return 0
}

func (x *NotifyExitReq) GetPublicIP() string {
	if x != nil {
		return x.PublicIP
	}
	return ""
}

// The NotifyExit RPC's response message
type NotifyExitRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *NotifyExitRes) Reset() {
	*x = NotifyExitRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyExitRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyExitRes) ProtoMessage() {}

func (x *NotifyExitRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyExitRes.ProtoReflect.Descriptor instead.
func (*NotifyExitRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyExitRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingServer RPC's Request Message
type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=Ping,proto3" json:"Ping,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{5}
}

func (x *PingReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

// PingServer RPC's Response Message
type PingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=Pong,proto3" json:"Pong,omitempty"`
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{6}
}

func (x *PingRes) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// Verify RPC's Request Message
type VerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Challenge string `protobuf:"bytes,1,opt,name=Challenge,proto3" json:"Challenge,omitempty"`
}

func (x *VerifyReq) Reset() {
	*x = VerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReq) ProtoMessage() {}

func (x *VerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReq.ProtoReflect.Descriptor instead.
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyReq) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

// Verify RPC's Response Message
type VerifyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *VerifyRes) Reset() {
	*x = VerifyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRes) ProtoMessage() {}

func (x *VerifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRes.ProtoReflect.Descriptor instead.
func (*VerifyRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// DataUpdate RPC's Request Message
type DataUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            UPDATE_TYPE `protobuf:"varint,1,opt,name=Type,proto3,enum=serverManagingService.UPDATE_TYPE" json:"Type,omitempty"`
	ChangedServerID int32       `protobuf:"varint,2,opt,name=ChangedServerID,proto3" json:"ChangedServerID,omitempty"`
	ServerData      *ServerData `protobuf:"bytes,3,opt,name=ServerData,proto3" json:"ServerData,omitempty"`
}

func (x *DataUpdateReq) Reset() {
	*x = DataUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUpdateReq) ProtoMessage() {}

func (x *DataUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUpdateReq.ProtoReflect.Descriptor instead.
func (*DataUpdateReq) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{9}
}

func (x *DataUpdateReq) GetType() UPDATE_TYPE {
	if x != nil {
		return x.Type
	}
	return UPDATE_TYPE_New
}

func (x *DataUpdateReq) GetChangedServerID() int32 {
	if x != nil {
		return x.ChangedServerID
	}
	return 0
}

func (x *DataUpdateReq) GetServerData() *ServerData {
	if x != nil {
		return x.ServerData
	}
	return nil
}

// DataUpdate RPC's Response Message
type DataUpdateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *DataUpdateRes) Reset() {
	*x = DataUpdateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_serverManaging_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUpdateRes) ProtoMessage() {}

func (x *DataUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_serverManaging_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUpdateRes.ProtoReflect.Descriptor instead.
func (*DataUpdateRes) Descriptor() ([]byte, []int) {
	return file_protofiles_serverManaging_proto_rawDescGZIP(), []int{10}
}

func (x *DataUpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protofiles_serverManaging_proto protoreflect.FileDescriptor

var file_protofiles_serverManaging_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x15, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x68, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x1b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x5f, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x12, 0x1d, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x49,
	0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x49, 0x50, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x36, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x12, 0x1d, 0x0a, 0x0a,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x49, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x49, 0x50, 0x22, 0x8f, 0x01, 0x0a, 0x10,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0xbb, 0x01,
	0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x34, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x58, 0x49, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x53, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x45, 0x52,
	0x56, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x05, 0x53, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x22, 0x29, 0x0a, 0x0d, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x50, 0x6f, 0x6e, 0x67, 0x22, 0x29, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22,
	0x23, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x36, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x12, 0x41, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x0d, 0x44,
	0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x48, 0x0a, 0x0b, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x50, 0x52, 0x4f,
	0x56, 0x49, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x41, 0x4c, 0x54,
	0x49, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x03,
	0x2a, 0x22, 0x0a, 0x09, 0x45, 0x58, 0x49, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a,
	0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x01, 0x2a, 0x2e, 0x0a, 0x0b, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x65, 0x77, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x10, 0x02, 0x32, 0xcd, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x61, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x58, 0x0a, 0x0a, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x45, 0x78, 0x69, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x78, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x32, 0x94, 0x02, 0x0a, 0x16, 0x45, 0x64, 0x67, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12,
	0x4c, 0x0a, 0x0a, 0x50, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x52, 0x0a,
	0x0c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x73, 0x12, 0x58, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x42, 0x18, 0x5a, 0x16, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_serverManaging_proto_rawDescOnce sync.Once
	file_protofiles_serverManaging_proto_rawDescData = file_protofiles_serverManaging_proto_rawDesc
)

func file_protofiles_serverManaging_proto_rawDescGZIP() []byte {
	file_protofiles_serverManaging_proto_rawDescOnce.Do(func() {
		file_protofiles_serverManaging_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_serverManaging_proto_rawDescData)
	})
	return file_protofiles_serverManaging_proto_rawDescData
}

var file_protofiles_serverManaging_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protofiles_serverManaging_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protofiles_serverManaging_proto_goTypes = []interface{}{
	(SERVER_TYPE)(0),         // 0: serverManagingService.SERVER_TYPE
	(EXIT_TYPE)(0),           // 1: serverManagingService.EXIT_TYPE
	(UPDATE_TYPE)(0),         // 2: serverManagingService.UPDATE_TYPE
	(*ServerData)(nil),       // 3: serverManagingService.ServerData
	(*PublishServerReq)(nil), // 4: serverManagingService.PublishServerReq
	(*PublishServerRes)(nil), // 5: serverManagingService.PublishServerRes
	(*NotifyExitReq)(nil),    // 6: serverManagingService.NotifyExitReq
	(*NotifyExitRes)(nil),    // 7: serverManagingService.NotifyExitRes
	(*PingReq)(nil),          // 8: serverManagingService.PingReq
	(*PingRes)(nil),          // 9: serverManagingService.PingRes
	(*VerifyReq)(nil),        // 10: serverManagingService.VerifyReq
	(*VerifyRes)(nil),        // 11: serverManagingService.VerifyRes
	(*DataUpdateReq)(nil),    // 12: serverManagingService.DataUpdateReq
	(*DataUpdateRes)(nil),    // 13: serverManagingService.DataUpdateRes
}
var file_protofiles_serverManaging_proto_depIdxs = []int32{
	0,  // 0: serverManagingService.PublishServerReq.Type:type_name -> serverManagingService.SERVER_TYPE
	3,  // 1: serverManagingService.PublishServerRes.ServerData:type_name -> serverManagingService.ServerData
	1,  // 2: serverManagingService.NotifyExitReq.Type:type_name -> serverManagingService.EXIT_TYPE
	0,  // 3: serverManagingService.NotifyExitReq.SType:type_name -> serverManagingService.SERVER_TYPE
	2,  // 4: serverManagingService.DataUpdateReq.Type:type_name -> serverManagingService.UPDATE_TYPE
	3,  // 5: serverManagingService.DataUpdateReq.ServerData:type_name -> serverManagingService.ServerData
	4,  // 6: serverManagingService.ServerHandling.PublishServer:input_type -> serverManagingService.PublishServerReq
	6,  // 7: serverManagingService.ServerHandling.NotifyExit:input_type -> serverManagingService.NotifyExitReq
	8,  // 8: serverManagingService.EdgeServerConnectivity.PingServer:input_type -> serverManagingService.PingReq
	10, // 9: serverManagingService.EdgeServerConnectivity.VerifyServer:input_type -> serverManagingService.VerifyReq
	12, // 10: serverManagingService.EdgeServerConnectivity.DataUpdate:input_type -> serverManagingService.DataUpdateReq
	5,  // 11: serverManagingService.ServerHandling.PublishServer:output_type -> serverManagingService.PublishServerRes
	7,  // 12: serverManagingService.ServerHandling.NotifyExit:output_type -> serverManagingService.NotifyExitRes
	9,  // 13: serverManagingService.EdgeServerConnectivity.PingServer:output_type -> serverManagingService.PingRes
	11, // 14: serverManagingService.EdgeServerConnectivity.VerifyServer:output_type -> serverManagingService.VerifyRes
	13, // 15: serverManagingService.EdgeServerConnectivity.DataUpdate:output_type -> serverManagingService.DataUpdateRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protofiles_serverManaging_proto_init() }
func file_protofiles_serverManaging_proto_init() {
	if File_protofiles_serverManaging_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_serverManaging_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishServerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyExitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyExitRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_serverManaging_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataUpdateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_serverManaging_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protofiles_serverManaging_proto_goTypes,
		DependencyIndexes: file_protofiles_serverManaging_proto_depIdxs,
		EnumInfos:         file_protofiles_serverManaging_proto_enumTypes,
		MessageInfos:      file_protofiles_serverManaging_proto_msgTypes,
	}.Build()
	File_protofiles_serverManaging_proto = out.File
	file_protofiles_serverManaging_proto_rawDesc = nil
	file_protofiles_serverManaging_proto_goTypes = nil
	file_protofiles_serverManaging_proto_depIdxs = nil
}
