// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package newServerHandling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NewServerHandlingClient is the client API for NewServerHandling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewServerHandlingClient interface {
	PublishServer(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*ServerInfoResponse, error)
}

type newServerHandlingClient struct {
	cc grpc.ClientConnInterface
}

func NewNewServerHandlingClient(cc grpc.ClientConnInterface) NewServerHandlingClient {
	return &newServerHandlingClient{cc}
}

func (c *newServerHandlingClient) PublishServer(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, "/halalwedd_managing_server.NewServerHandling/publishServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewServerHandlingServer is the server API for NewServerHandling service.
// All implementations must embed UnimplementedNewServerHandlingServer
// for forward compatibility
type NewServerHandlingServer interface {
	PublishServer(context.Context, *ServerInfo) (*ServerInfoResponse, error)
	mustEmbedUnimplementedNewServerHandlingServer()
}

// UnimplementedNewServerHandlingServer must be embedded to have forward compatible implementations.
type UnimplementedNewServerHandlingServer struct {
}

func (UnimplementedNewServerHandlingServer) PublishServer(context.Context, *ServerInfo) (*ServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishServer not implemented")
}
func (UnimplementedNewServerHandlingServer) mustEmbedUnimplementedNewServerHandlingServer() {}

// UnsafeNewServerHandlingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewServerHandlingServer will
// result in compilation errors.
type UnsafeNewServerHandlingServer interface {
	mustEmbedUnimplementedNewServerHandlingServer()
}

func RegisterNewServerHandlingServer(s grpc.ServiceRegistrar, srv NewServerHandlingServer) {
	s.RegisterService(&NewServerHandling_ServiceDesc, srv)
}

func _NewServerHandling_PublishServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewServerHandlingServer).PublishServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/halalwedd_managing_server.NewServerHandling/publishServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewServerHandlingServer).PublishServer(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// NewServerHandling_ServiceDesc is the grpc.ServiceDesc for NewServerHandling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewServerHandling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "halalwedd_managing_server.NewServerHandling",
	HandlerType: (*NewServerHandlingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "publishServer",
			Handler:    _NewServerHandling_PublishServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofiles/newServerHandling.proto",
}
